### ISSUE TITLE
Library does not compile with Xcode 6.

### ISSUE THREAD

**Issue by marcopapa** [carlj/libFIOApi#2]
See the attached. The problem are the three variables _finished, _executing and _cancelled in  ConcurrentOperation.m/.h:

![screen shot 2015-02-03 at 10 06 23 am](https://cloud.githubusercontent.com/assets/329291/6026134/d56c4794-ab8c-11e4-9742-e8a9cf5d535d.png)
![screen shot 2015-02-03 at 10 07 00 am](https://cloud.githubusercontent.com/assets/329291/6026135/d7427502-ab8c-11e4-8872-663a10681b4b.png)

 snapshots.

**Comment by marcopapa** [comment]
Adding these gets rid of the 'undeclared identifier' errors:

@synthesize finished = _finished;
@synthesize executing = _executing;
@synthesize cancelled = _cancelled;

I still get some warning int eh .H file:

![screen shot 2015-02-03 at 10 51 32 am](https://cloud.githubusercontent.com/assets/329291/6026853/d940f0f8-ab92-11e4-8c71-13c997d0b66e.png)

**Comment by carlj** [comment]
fixed in commit b9f5a4b71b40a3dae4203ece5f4ecad87d99d750
